"""
Django settings for Exam project.
Generated by 'django-admin startproject' using Django 5.2.7
"""

from pathlib import Path
import os
from urllib.parse import urlparse

# ✅ load .env (local साठी)
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent


# ==========================
# SECURITY
# ==========================
SECRET_KEY = 'django-insecure-jndak*3#w9mpef7@+72@zi8!yeqm-#@sm5x9n_#_d=r*w6lty_'
DEBUG = True

# ✅ Render + Local
ALLOWED_HOSTS = [
    "exam-portal-1-7ha0.onrender.com",
    "localhost",
    "127.0.0.1",
]

# ==========================
# INSTALLED APPS
# ==========================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # ✅ your app
    "mcq",
]


# ==========================
# MIDDLEWARE
# ==========================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # ✅ for Render static
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "Exam.urls"


# ==========================
# TEMPLATES
# ==========================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "Exam.wsgi.application"


# ==========================
# DATABASE (Railway MySQL Public URL)
# ==========================
MYSQL_PUBLIC_URL = os.environ.get("MYSQL_PUBLIC_URL")


url = urlparse(MYSQL_PUBLIC_URL)

DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": url.path[1:],  # "/railway" -> "railway"
            "USER": url.username,
            "PASSWORD": url.password,
            "HOST": url.hostname,  # maglev.proxy.rlwy.net
            "PORT": url.port,      # 44186
        }
    }

# ==========================
# PASSWORD VALIDATION
# ==========================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# ==========================
# LANGUAGE / TIME
# ==========================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Kolkata"
USE_I18N = True
USE_TZ = True


# ==========================
# STATIC FILES (Render)
# ==========================
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# ✅ WhiteNoise static
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# ==========================
# DEFAULT AUTO FIELD
# ==========================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
